/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\Github\\boilerplate\\gganbu-vuepress\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-2966df8a",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2966df8a").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-55fa3964",
    path: "/guide/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55fa3964").then(next)
    },
  },
  {
    path: "/guide/index.html",
    redirect: "/guide/"
  },
  {
    name: "v-359ea05a",
    path: "/guide/guide.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-359ea05a").then(next)
    },
  },
  {
    name: "v-4277e234",
    path: "/hooks/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4277e234").then(next)
    },
  },
  {
    path: "/hooks/index.html",
    redirect: "/hooks/"
  },
  {
    name: "v-6de4486e",
    path: "/intro/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6de4486e").then(next)
    },
  },
  {
    path: "/intro/index.html",
    redirect: "/intro/"
  },
  {
    name: "v-1e32689e",
    path: "/middleware/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e32689e").then(next)
    },
  },
  {
    path: "/middleware/index.html",
    redirect: "/middleware/"
  },
  {
    name: "v-463961be",
    path: "/router/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-463961be").then(next)
    },
  },
  {
    path: "/router/index.html",
    redirect: "/router/"
  },
  {
    name: "v-5ad5b144",
    path: "/usage/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ad5b144").then(next)
    },
  },
  {
    path: "/usage/index.html",
    redirect: "/usage/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]