/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "Gganbu",
  "description": "Just playing around",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "你好 guide",
      "frontmatter": {},
      "regularPath": "/guide/",
      "relativePath": "guide/README.md",
      "key": "v-55fa3964",
      "path": "/guide/"
    },
    {
      "title": "1111",
      "frontmatter": {},
      "regularPath": "/guide/guide.html",
      "relativePath": "guide/guide.md",
      "key": "v-359ea05a",
      "path": "/guide/guide.html"
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "/logo.jpg",
        "actionText": "快速上手 →",
        "actionLink": "/guide/",
        "features": [
          {
            "title": "一体化开发",
            "details": "前后端一体化开发，在 src 一个目录下开发前后端代码"
          },
          {
            "title": "零Api调用",
            "details": "从 controller（可配置）目录 引入函数，调用函数自动转换为 Api 请求"
          },
          {
            "title": "零 Route 配置",
            "details": "按照文件所在路径 自动配置 Route"
          }
        ],
        "footer": "MIT Licensed | Copyright © 2021-present Sanjay Huang"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-2966df8a",
      "path": "/"
    },
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/intro/",
      "relativePath": "intro/README.md",
      "key": "v-6de4486e",
      "path": "/intro/",
      "headers": [
        {
          "level": 2,
          "title": "✨ 特性",
          "slug": "✨-特性"
        },
        {
          "level": 2,
          "title": "示例",
          "slug": "示例"
        }
      ]
    },
    {
      "title": "Hooks",
      "frontmatter": {},
      "regularPath": "/hooks/",
      "relativePath": "hooks/README.md",
      "key": "v-4277e234",
      "path": "/hooks/",
      "headers": [
        {
          "level": 2,
          "title": "内置 Hook",
          "slug": "内置-hook"
        },
        {
          "level": 3,
          "title": "useContext",
          "slug": "usecontext"
        },
        {
          "level": 2,
          "title": "自定义 Hook",
          "slug": "自定义-hook"
        }
      ]
    },
    {
      "title": "中间件",
      "frontmatter": {},
      "regularPath": "/middleware/",
      "relativePath": "middleware/README.md",
      "key": "v-1e32689e",
      "path": "/middleware/",
      "headers": [
        {
          "level": 2,
          "title": "全局中间件",
          "slug": "全局中间件"
        },
        {
          "level": 2,
          "title": "文件中间件",
          "slug": "文件中间件"
        },
        {
          "level": 2,
          "title": "路由中间件",
          "slug": "路由中间件"
        }
      ]
    },
    {
      "title": "路由",
      "frontmatter": {},
      "regularPath": "/router/",
      "relativePath": "router/README.md",
      "key": "v-463961be",
      "path": "/router/",
      "headers": [
        {
          "level": 2,
          "title": "默认解析",
          "slug": "默认解析"
        },
        {
          "level": 2,
          "title": "路由设置",
          "slug": "路由设置"
        }
      ]
    },
    {
      "title": "快速上手",
      "frontmatter": {},
      "regularPath": "/usage/",
      "relativePath": "usage/README.md",
      "key": "v-5ad5b144",
      "path": "/usage/",
      "headers": [
        {
          "level": 2,
          "title": "安装",
          "slug": "安装"
        },
        {
          "level": 2,
          "title": "vite 配置",
          "slug": "vite-配置"
        },
        {
          "level": 2,
          "title": "示例",
          "slug": "示例"
        }
      ]
    }
  ],
  "themeConfig": {
    "nav": [
      {
        "text": "Home",
        "link": "/"
      },
      {
        "text": "Guide",
        "link": "/guide/"
      }
    ],
    "sidebar": [
      {
        "title": "介绍",
        "path": "/intro/"
      },
      {
        "title": "快速上手",
        "path": "/usage/"
      },
      {
        "title": "Hooks",
        "path": "/hooks/"
      },
      {
        "title": "中间件",
        "path": "/middleware/"
      },
      {
        "title": "路由",
        "path": "/router/"
      }
    ]
  }
}